# Análisis de ventas y generación de insights
En este notebook se realiza el análisis descriptivo y estadístico del dataset final, con el objetivo de obtener insights de negocio y preparar la información para su visualización en Power BI.

# Importaciones

In [2]:
import pandas as pd
import numpy as np

# Carga del dataset final

In [3]:
df = pd.read_csv(
    "../data/processed_data/retail_final_dataset.csv",
    parse_dates=["Order Date", "Ship Date"]
)

# KPIs principales

In [4]:
total_sales = df["Sales"].sum()
avg_order_value = df["Sales"].mean()
total_orders = df["Order ID"].nunique()
total_customers = df["Customer ID"].nunique()
total_quantity = df["Quantity"].sum()

total_sales, avg_order_value, total_orders, total_customers, total_quantity

(np.float64(12642501.90988),
 np.float64(246.4905812025736),
 25035,
 1590,
 np.int64(178312))

# Análisis temporal de ventas
Variables temporales.
Ventas por año.

In [5]:
df["Order Year"] = df["Order Date"].dt.year
df["Order Month"] = df["Order Date"].dt.month
df["Order Month Name"] = df["Order Date"].dt.month_name()

sales_by_year = df.groupby("Order Year")["Sales"].sum().reset_index()
sales_by_year

   Order Year         Sales
0        2011  2.259451e+06
1        2012  2.677439e+06
2        2013  3.405746e+06
3        2014  4.299866e+06

# Análisis por categoría y producto

## Venta por categoría

In [6]:
sales_by_category = (
    df.groupby("Category")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

## Top 10

In [8]:
top_products = (
    df.groupby("Product Name")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

top_products

                                        Product Name       Sales
0                       Apple Smart Phone, Full Size  86935.7786
1                       Cisco Smart Phone, Full Size  76441.5306
2                    Motorola Smart Phone, Full Size  73156.3030
3                       Nokia Smart Phone, Full Size  71904.5555
4              Canon imageCLASS 2200 Advanced Copier  61599.8240
5         Hon Executive Leather Armchair, Adjustable  58193.4841
6  Office Star Executive Leather Armchair, Adjust...  50661.6840
7  Harbour Creations Executive Leather Armchair, ...  50121.5160
8                      Samsung Smart Phone, Cordless  48653.4600
9                  Nokia Smart Phone, with Caller ID  47877.7857

## Análisis geográfico
Ventas por pais

In [9]:
sales_by_country = (
    df.groupby("Country")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

sales_by_country.head(10)

          Country         Sales
0   United States  2.297201e+06
1       Australia  9.252359e+05
2          France  8.589311e+05
3           China  7.005620e+05
4         Germany  6.288400e+05
5          Mexico  6.225906e+05
6           India  5.896501e+05
7  United Kingdom  5.285763e+05
8       Indonesia  4.048875e+05
9          Brazil  3.611064e+05

## Segmentación de clientes

In [10]:
sales_by_segment = (
    df.groupby("Segment")["Sales"]
    .sum()
    .reset_index()
)

sales_by_segment

       Segment         Sales
0     Consumer  6.507949e+06
1    Corporate  3.824698e+06
2  Home Office  2.309855e+06

## Preparación de datasets para Power BI

In [11]:
sales_by_year.to_csv(
    "../data/processed_data/sales_by_year.csv",
    index=False
)

sales_by_category.to_csv(
    "../data/processed_data/sales_by_category.csv",
    index=False
)

sales_by_country.to_csv(
    "../data/processed_data/sales_by_country.csv",
    index=False
)

sales_by_segment.to_csv(
    "../data/processed_data/sales_by_segment.csv",
    index=False
)

## Conclusiones del análisis
El análisis muestra patrones claros en la evolucion temporal de las ventas, una concentración de ingresos en determinadas categorías y países, y diferencias significativas entre segmentos de clientes. Estos insights permiten orientar estrategias comeciales y de optimizació de catálogo.